name: Ruby and Node

on:
  push: 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6'
        bundler-cache: true
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Build and test
      run: |
        bundle exec middleman build
